modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
[[mods]]
modId="questapi"
version="1.2.0"
displayName="Quest API"
logoFile="questapi.png"
authors="Zanckor"
description='''

'''
[[dependencies.questapi]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.questapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
